### MATH2504 S2, 2023, BigHW Submission 
### Submission form II of IV 

Student #1 name: Matthew Lynch

Student #1 ID: 47426557

Student #2 name: Felicity Caruana

Student #2 ID: 47425523

GitHub repo: https://github.com/lynchmatt/Matthew-Lynch_Felicity-Caruana-2504-2023-BigHW

---

**Note: It is expected that this notebook be runnable in the sense that the marker can select "Restart & Run All" and all code cells of solutions will execute. This requires not to have name clashes between solutions.**

---

# Solution to [Question 5](https://courses.smp.uq.edu.au/MATH2504/2023/assessment_html/bighw.html#q5)

## 5a:

In [ ]:
### This code finds all the abundant numbers from 1 to 200, using divisors() from Primes.jl

import Pkg; Pkg.add("Primes")
using Primes

function abundant_finder_1()
    for i in 1:200
        div = divisors(i)
        total = sum(div) - i
        if total > i
            println("Abundant number found: ", i)
        else
            continue
        end
    end
end

abundant_finder_1()

## 5b:

In [ ]:
### This code makes a function to find divisors of a number, then implements it to find the abundant numbers 
### up to 200.

function my_divisor_finder(n)
    divlist = [i for i in 1:200 if n % i ==0]
    return divlist
end

# Now make another abundant number-finder, using the new divisor function my_divisor_finder

function abundant_finder_2()
    for i in 1:200
        divlist = my_divisor_finder(i)
        total = sum(divlist) - i
        if total > i
            println("Abundant number found: ", i)
        else
            continue
        end
    end
end

abundant_finder_2()

---

*Use this area below as an experimental playground for the question. Feel free to leave some of the experimental code here with your submision. However, it will not be marked or reviewed. Make sure in your submission that if there is any experimental code here then running it does not interfere with running the actual solutions.*

---

# Solution to [Question 6](https://courses.smp.uq.edu.au/MATH2504/2023/assessment_html/bighw.html#q6)

In [ ]:
### Answer 6 here (in place of this comment)

---

*Use this area below as an experimental playground for the question. Feel free to leave some of the experimental code here with your submision. However, it will not be marked or reviewed. Make sure in your submission that if there is any experimental code here then running it does not interfere with running the actual solutions.*

---

# Solution to [Question 7](https://courses.smp.uq.edu.au/MATH2504/2023/assessment_html/bighw.html#q7)

## 7a:

In [1]:
### Answer 7a here (in place of this comment)
# install packages (REMEMBER TO UNCOMMENT)
# import Pkg; Pkg.add("Measures")
# import Pkg; Pkg.add("Plots")
# import Pkg; Pkg.add("LaTeXStrings")
using Plots, LaTeXStrings, Measures

# define sequences
fn1(n) = 1 - 1/√(20n)
fn2(n) = 1 - exp(-(n-1)/50)
fn3(n) = max(min(1, n/600 + 0.2),0)
fn4(n) = 1/(1+exp(-(n - 100)/200))


# define domain and range
xVals, yVals = 0:1:600, 0:10

# plot sequences REMEMBER TO UNCOMMENT
# plot(xVals, [fn1.(xVals), fn2.(xVals), fn3.(xVals), fn4.(xVals)], 
#    label=["Function 1" "Function 2" "Function 3" "Function 4"], 
#    seriestype=:scatter, m=(:dot, 2), markerstrokewidth=0, ma=0.5,
#    title="Functions")

(0:1:600, 0:10)

## 7b:

In [62]:
## This code makes a function that finds the smallest n where f(n) is greater than a target number.

function find_n_basic(f::Function, target::Number)
    n = 0
    while f(n) < target
        n = n + 1
    end
    println("Smallest n where $f is greater than $target is $n.")
end

# create lists for easy iteration of each function over different example target values
functions = [fn1, fn2, fn3, fn4]
example_values = [0.2, 0.4, 0.6, 0.8]

for f in functions
    for v in example_values
        find_n_basic(f, v)
    end
    println()
end

Smallest n where fn1 is greater than 0.2 is 1.
Smallest n where fn1 is greater than 0.4 is 1.
Smallest n where fn1 is greater than 0.6 is 1.
Smallest n where fn1 is greater than 0.8 is 2.

Smallest n where fn2 is greater than 0.2 is 13.
Smallest n where fn2 is greater than 0.4 is 27.
Smallest n where fn2 is greater than 0.6 is 47.
Smallest n where fn2 is greater than 0.8 is 82.

Smallest n where fn3 is greater than 0.2 is 0.
Smallest n where fn3 is greater than 0.4 is 120.
Smallest n where fn3 is greater than 0.6 is 240.
Smallest n where fn3 is greater than 0.8 is 360.

Smallest n where fn4 is greater than 0.2 is 0.
Smallest n where fn4 is greater than 0.4 is 19.
Smallest n where fn4 is greater than 0.6 is 182.
Smallest n where fn4 is greater than 0.8 is 378.



## 7c:

In [63]:
### Answer 7c here (in place of this comment)
function find_n_geometric(f::Function, target::Number)
    n = 0
    if f(n) >= target
        println("Smallest n where $f is greater than $target is $(n).")
    else
        n = 1
        exponent = 1
        while f(n) < target
            n = 2^(exponent)
            exponent = exponent+1
        end
    while f(n) >= target
        n = n-1
    end
    println("Smallest n where $f is greater than $target is $(n+1).")
    end 
end

for f in functions
    for v in example_values
        find_n_geometric(f, v)
    end
    println()
end

Smallest n where fn1 is greater than 0.2 is 1.
Smallest n where fn1 is greater than 0.4 is 1.
Smallest n where fn1 is greater than 0.6 is 1.
Smallest n where fn1 is greater than 0.8 is 2.

Smallest n where fn2 is greater than 0.2 is 13.
Smallest n where fn2 is greater than 0.4 is 27.
Smallest n where fn2 is greater than 0.6 is 47.
Smallest n where fn2 is greater than 0.8 is 82.

Smallest n where fn3 is greater than 0.2 is 0.
Smallest n where fn3 is greater than 0.4 is 120.
Smallest n where fn3 is greater than 0.6 is 240.
Smallest n where fn3 is greater than 0.8 is 360.

Smallest n where fn4 is greater than 0.2 is 0.
Smallest n where fn4 is greater than 0.4 is 19.
Smallest n where fn4 is greater than 0.6 is 182.
Smallest n where fn4 is greater than 0.8 is 378.



## 7d:

In [ ]:
# iterative binary search
function binary_search(f:: Function, exponent::Number, target::Number)
    low = 2^(exponent)
    high = 2^(exponent+1)
    mid = (low+high)/2
    while (high-low) >= 1
        mid = (low+high)/2
        if target == f(mid)
            println("Smallest n where $f is greater than $target is ", mid)
            return mid
        elseif f(mid) < target
            low = mid
        else
            high = mid
        end
    end
    if f(floor(mid)) > target && f(ceil(mid)) > target
        println("Smallest n where $f is greater than $target is ", floor(mid))
    elseif f(floor(mid)) < target && f(ceil(mid)) > target
        println("Smallest n where $f is greater than $target is ", ceil(mid))
    end
end

# function using binary search
function find_n_fast(f::Function, target::Number)
    n = 0
    if f(n) >= target
        println("Smallestwhere $f is greater than $target is $(n).")
        return target
    else
        n = 1
        if f(n) >= target
            println("Smallest n where $f is greater than $target is $(n).")
            return target
        else
            exponent = 1
            while (f(n) < target) && (f(2^(exponent+1)) < target)
                exponent = exponent+1
                n = 2^exponent
            end
            binary_search(f, exponent, target)
        end
    end
end

for f in functions
    for v in example_values
        find_n_fast(f, v)
    end
    println()
end

---

*Use this area below as an experimental playground for the question. Feel free to leave some of the experimental code here with your submision. However, it will not be marked or reviewed. Make sure in your submission that if there is any experimental code here then running it does not interfere with running the actual solutions.*

---

# Solution to [Question 8](https://courses.smp.uq.edu.au/MATH2504/2023/assessment_html/bighw.html#q8)

## 8a:

In [ ]:
### Answer 8a here (in place of this comment)

## 8b:

In [ ]:
### Answer 8b here (in place of this comment)

## 8c:

In [ ]:
### Answer 8c here (in place of this comment)

## 8d:

In [ ]:
### Answer 8d here (in place of this comment)

---

*Use this area below as an experimental playground for the question. Feel free to leave some of the experimental code here with your submision. However, it will not be marked or reviewed. Make sure in your submission that if there is any experimental code here then running it does not interfere with running the actual solutions.*

---

# Solution to [Question 9](https://courses.smp.uq.edu.au/MATH2504/2023/assessment_html/bighw.html#q9)

## 9a:

In [167]:
# Function for matrix multiplication via linear combination of 
# columns.
function my_mult_by_cols(A,B)
    rowsA, columnsA = size(A)
    rowsB, columnsB = size(B)
    # make sures columnsA = rowsB
    @assert columnsA == rowsB
    # initialise C
    C = zeros(rowsA, columnsB)
    for j in 1:columnsB
        C[:,j] = sum(B[i,j]*A[:,i] for i in 1:rowsB)
    end
    return C
end

# Set random matrices A and B as examples
using LinearAlgebra
using Random
#Random.seed!(0)
A = round.(10*rand(2,2)) # gives a 2x3 matrix
B = round.(10*rand(2,2)) # gives a 3x4 matrix
display(A*B)

# check the function works
display(my_mult_by_cols(A,B))

2×2 Matrix{Float64}:
 2.0  6.0
 4.0  3.0

2×2 Matrix{Float64}:
 9.0  3.0
 1.0  6.0

2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

## 9b:

In [169]:
# Function for matrix multiplication via linear combination of 
# rows

function my_mult_by_rows(A,B)
    rowsA, columnsA = size(A)
    rowsB, columnsB = size(B)
    # make sures columnsA = rowsB
    @assert columnsA == rowsB
    # initialise C
    C = zeros(rowsA, columnsB)
    for i in 1:rowsA
        C[i,:] = sum(B[j,:]*A[i,j] for j in 1:columnsA)
    end
    return C
end

# check the function works
display(A*B)
display(my_mult_by_rows(A,B))

2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

## 9c:

In [181]:
### Function to 
function my_mult_outer_products(A,B)
    rowsA, columnsA = size(A)
    rowsB, columnsB = size(B)
    # make sures columnsA = rowsB
    @assert columnsA == rowsB
    # initialise C
    C = zeros(rowsA, columnsB)
    sum = zeros(rowsA, columnsB)
    iteration = zeros(rowsA, columnsB)
    for j in 1:columnsA
        iteration = A[:,j]*B[j,:]'
        sum += iteration
    end
    return sum
end

my_mult_outer_products(A,B)

2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

## 9d:


The efficiency of the various functions can be compared using Benchmark tools. This will time the functions, so we can see if a nested loop is any slower than using list comprehensions (as in 9a and 9b) or a single loop (as in 9c).

The code below shows that my_mult_inner_products is not consistently faster or slower than the functions in 9a-c. Even when it's slower, it is often by less than a microsecond. Therefore, even though having a single loop is less complex, the functions without nested loops are not consistently or noticeable more efficient than my_mult_inner_products.

Accessing elements in a matrix is O(1), but accessing many elements in a matrix can take different amounts of time based on the dimensions of the matrix. This is because the dimensions of the matrix changes where the elements of the matrix are physically stored in memory. As a result, accessing all the elements of a matrix can occur faster or slower depending on things such as whether the columns or rows are accessed first.

In [193]:
# import packages
# import Pkg; Pkg.add("BenchmarkTools")
using BenchmarkTools

# copy the supplied code for multiplication by inner products
function my_mult_inner_products(A,B)
    nA,mA = size(A)
    nB,mB = size(B)
    @assert mA == nB
    n, m, p = nA, mA, mB
    C = Array{Float64}(undef,n,p)

    for i in 1:n
        for j in 1:p
            C[i,j] = A[i,:]' * B[:,j] #compute inner product of i'th row of A and j'th column of B
        end
    end
    return C
end


@btime my_mult_inner_products(A,B)
@btime my_mult_by_cols(A,B)
@btime my_mult_by_rows(A,B)
@btime my_mult_outer_products(A,B)


  240.909 ns (9 allocations: 736 bytes)
  476.471 ns (15 allocations: 1.19 KiB)
  454.545 ns (11 allocations: 896 bytes)
  323.438 ns (11 allocations: 992 bytes)


2×2 Matrix{Float64}:
 24.0  42.0
 39.0  30.0

---

*Use this area below as an experimental playground for the question. Feel free to leave some of the experimental code here with your submision. However, it will not be marked or reviewed. Make sure in your submission that if there is any experimental code here then running it does not interfere with running the actual solutions.*

---

2×2 Matrix{Float64}:
 4.0  4.0
 6.0  6.0

2×2 Matrix{Float64}:
 9.0  8.0
 5.0  1.0

2×2 Matrix{Float64}:
 56.0  36.0
 84.0  54.0

2×2 Matrix{Float64}:
 56.0  36.0
 84.0  54.0